---
# PVC
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: snapshot-storage-pv
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: ""
#   hostPath:
#     path: /mnt/shared-data
---
# ES and Kibana resources
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-cluster-1
  namespace: cluster-1
spec:
  version: 8.18.1
  nodeSets:
  - name: master
    count: 1
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          # volumeMounts:
          # - name: snapshot-storage
          #   mountPath: /tmp/snapshots
          resources:
            requests:
              memory: 2Gi
              cpu: 2
            limits:
              memory: 2.5Gi
    config:
      node.roles: ["master"]
      node.store.allow_mmap: false
      xpack.http.ssl.verification_mode: "none"
  - name: data
    count: 2
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          # volumeMounts:
          # - name: snapshot-storage
          #   mountPath: /tmp/snapshots
          resources:
            requests:
              memory: 2Gi
              cpu: 2
            limits:
              memory: 2.5Gi
    config:
      node.roles: ["data", "ingest", "data_hot", "data_frozen"]
      node.store.allow_mmap: false
      xpack.http.ssl.verification_mode: "none"
  auth:
    fileRealm:
    - secretName: elastic-credentials
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kb-cluster-1
  namespace: cluster-1
spec:
  version: 8.18.1
  count: 1
  elasticsearchRef:
    name: es-cluster-1
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: snapshot-storage
#   namespace: cluster-1
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: ""
#   volumeName: snapshot-storage-pv
---
# Monitoring ckuster
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-cluster-2
  namespace: cluster-2
spec:
  version: 8.18.1
  nodeSets:
  - name: master
    count: 1
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          # volumeMounts:
          # - name: snapshot-storage
          #   mountPath: /tmp/snapshots
          resources:
            requests:
              memory: 2Gi
              cpu: 2
            limits:
              memory: 2.5Gi
    config:
      node.roles: ["master"]
      node.store.allow_mmap: false
      xpack.http.ssl.verification_mode: "none"
  - name: data
    count: 2
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          # volumeMounts:
          # - name: snapshot-storage
          #   mountPath: /tmp/snapshots
          resources:
            requests:
              memory: 2Gi
              cpu: 2
            limits:
              memory: 2.5Gi
    config:
      node.roles: ["data", "ingest"]
      node.store.allow_mmap: false
      xpack.http.ssl.verification_mode: "none"
  auth:
    fileRealm:
    - secretName: elastic-credentials
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kb-cluster-2
  namespace: cluster-2
spec:
  version: 8.18.1
  count: 1
  elasticsearchRef:
    name: es-cluster-2
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=1024"
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 2.5Gi
            cpu: 1
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: snapshot-storage
#   namespace: cluster-2
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: ""
#   volumeName: snapshot-storage-pv
...