apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: __NAMESPACE__
spec:
  version: __ES_VERSION__
  nodeSets:
    - name: default
      count: 1
      config:
        node.roles: ["master", "data_hot", "data_content", "ingest", "ml", "remote_cluster_client"]
        xpack.ml.model_repository: "http://elser-model-repository.__NAMESPACE__.svc.cluster.local"
        xpack.ml.use_auto_machine_memory_percent: true
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  cpu: "2"
                  memory: 6Gi
                limits:
                  memory: 6Gi
