---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es
  namespace: eck
spec:
  version: ${ecs_version}
  secureSettings:
  - secretName: azure-snapshot-secrets
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
      azure.client.default.endpoint_suffix: "ignored;BlobEndpoint=https://${sc_name}.blob.core.windows.net"
    podTemplate:
      metadata:
        annotations:
          traffic.sidecar.istio.io/includeInboundPorts: "*"
          traffic.sidecar.istio.io/excludeOutboundPorts: "9300"
          traffic.sidecar.istio.io/excludeInboundPorts: "9300"
  http:
    tls:
      selfSignedCertificate:
        disabled: true