---
# ES and Kibana resources
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-dev
  namespace: development
spec:
  version: 8.17.1
  nodeSets:
  - name: default
    count: 2
    config:
      node.store.allow_mmap: false
      xpack.security.audit.enabled: true
      xpack.security.audit.logfile.events.include: "authentication_success"
      xpack.security.audit.logfile.events.emit_request_body: true
      xpack.security.audit.logfile.events.ignore_filters.system.users: ["*_system", "found-internal-*",  "_xpack_security", "_xpack", "elastic/fleet-server","_async_search", "found-internal-admin-proxy"]
      xpack.security.audit.logfile.events.ignore_filters.realm.realms : [ "_es_api_key" ]
      xpack.security.audit.logfile.events.ignore_filters.internal_system.indices : ["*ml-inference-native-*", "*monitoring-es-*"]
      xpack.http.ssl.verification_mode: "none"
    podTemplate:
      metadata:
        labels:
          scrape: es
        annotations:
          co.elastic.logs/enabled: "true"
      spec:
        containers:
          - name: filebeat
            env:
            - name: ES_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: elastic-credentials
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: elastic-credentials
            command: ["/bin/sh", "-c"]
            args:
              - >
                filebeat -c /etc/filebeat-config/filebeat.yml
                -E setup.template.name=elastic-logs-8
                -E setup.template.pattern=elastic-logs-8*
                -E output.elasticsearch.index=elastic-logs-8
                -E output.elasticsearch.username=$(ES_USERNAME)
                -E output.elasticsearch.password=$(ES_PASSWORD)
                -e
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: standard
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: es-mon
        namespace: observability
    logs:
      elasticsearchRefs:
      - name: es-mon
        namespace: observability
  auth:
    fileRealm:
    - secretName: elastic-credentials
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kb-dev
  namespace: development
spec:
  version: 8.17.1
  count: 1
  elasticsearchRef:
    name: es-dev
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: es-mon
        namespace: observability
    logs:
      elasticsearchRefs:
      - name: es-mon
        namespace: observability
  config:
    # https://www.elastic.co/guide/en/kibana/current/monitoring-metricbeat.html
    monitoring.kibana.collection.enabled: false
    xpack.security.audit.enabled: true
    xpack.security.audit.ignore_filters:
    - categories: [web]
    - actions: [saved_object_open_point_in_time, saved_object_close_point_in_time, saved_object_find, space_find]
  podTemplate:
    metadata:
      labels:
        scrape: kb
      annotations:
        co.elastic.logs/enabled: "true"
    spec:
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=1024"
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 1.5Gi
            cpu: 1
      - name: filebeat
        env:
          - name: ES_VERSION
            value: "8.17.1"
          - name: ES_CLUSTER
            value: "es-dev"
          - name: ES_USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: elastic-credentials
          - name: ES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: elastic-credentials
        command: ["/bin/sh", "-c"]
        args:
          - >
            filebeat -c /etc/filebeat-config/filebeat.yml
            -E setup.template.name=elastic-logs-8
            -E setup.template.pattern=elastic-logs-8*
            -E output.elasticsearch.index=elastic-logs-8
            -E output.elasticsearch.username=$(ES_USERNAME)
            -E output.elasticsearch.password=$(ES_PASSWORD)
            -E processors.2.add_fields.fields={service.name:$(ES_CLUSTER)} 
            -E processors.2.add_fields.fields={service.version:$(ES_VERSION)}
            -e